// GnomeEQ — an 11-band system equalizer driven from the top bar.
//
// The DSP is not in here. It lives in PipeWire, as a filter-chain virtual
// sink generated by tools/gen_sink_conf.py and served by the system's own
// filter-chain.service. This extension is the control surface: it installs
// that chain if needed, keeps GSettings and the graph in agreement, and puts
// a menu in the panel.
//
// One consequence worth stating: because the DSP is independent of the Shell,
// disabling this extension does NOT stop the equalizer. Audio keeps flowing
// through the chain with the gains last set. That is deliberate — an
// equalizer is part of the audio configuration, not a property of the panel
// icon, and tearing down someone's audio routing on lock or on an extension
// update would be far more surprising than leaving it in place.

import GLib from 'gi://GLib';

import * as Main from 'resource:///org/gnome/shell/ui/main.js';
import { Extension } from 'resource:///org/gnome/shell/extensions/extension.js';

import * as C from './lib/constants.js';
import { PipeWireEQ } from './lib/pipewire.js';
import { GnomeEQIndicator } from './lib/indicator.js';

export default class GnomeEQExtension extends Extension {
    enable() {
        this._settings = this.getSettings();
        this._engine = new PipeWireEQ(this.path);
        this._indicator = new GnomeEQIndicator(this, this._engine);
        Main.panel.addToStatusArea('gnomeeq', this._indicator);

        this._settingsIds = [
            this._settings.connect(`changed::${C.Keys.GAINS}`,
                () => this._pushToGraph()),
            this._settings.connect(`changed::${C.Keys.PREAMP}`,
                () => this._pushToGraph()),
            this._settings.connect(`changed::${C.Keys.AUTO_PREAMP}`,
                () => this._pushToGraph()),
            this._settings.connect(`changed::${C.Keys.ENABLED}`,
                () => this._pushToGraph()),
        ];

        this._startEngine().catch(error => {
            logError(error, 'GnomeEQ: could not start the audio engine');
            Main.notifyError('GnomeEQ',
                'Could not set up the audio engine. See the journal for details.');
        });
    }

    disable() {
        // Tear down only what belongs to the Shell. The audio chain is left
        // running on purpose — see the note at the top of this file.
        for (const id of this._settingsIds ?? [])
            this._settings.disconnect(id);
        this._settingsIds = [];

        if (this._indicator) {
            this._indicator.destroy();
            this._indicator = null;
        }
        if (this._engine) {
            this._engine.destroy();
            this._engine = null;
        }
        this._settings = null;
    }

    // Install the chain if it is missing or out of date, make sure the daemon
    // serving it is actually running, take the default sink so every app is
    // covered, then push the stored curve into the graph.
    async _startEngine() {
        if (!await this._engine.ensureEngine()) {
            Main.notifyError('GnomeEQ',
                'The GnomeEQ audio sink did not appear. Check ' +
                '`systemctl --user status filter-chain.service`.');
            return;
        }

        await this._applyRouting();
        this._pushToGraph();
    }

    // The sink can vanish while the Shell keeps running: a PipeWire restart
    // takes filter-chain.service down with it and nothing starts it again (see
    // PipeWireEQ.ensureEngine). Audio falls back to the hardware silently, so
    // there is no moment at which we could have warned anyone — the first
    // symptom is moving a slider and hearing nothing change. Opening this menu
    // is exactly what someone does next, so use it as the cue to put the chain
    // back and re-push the curve, quietly and only when the sink is missing.
    async recoverEngine() {
        if (!this._engine || await this._engine.isEngineRunning())
            return;
        if (!await this._engine.ensureEngine())
            return;

        // The daemon restarted, so the node ids are new: the output pin and
        // the default-sink claim both have to be re-applied.
        await this._applyRouting();
        this._pushToGraph();
    }

    async _applyRouting() {
        if (!this._engine || !this._settings)
            return;

        const device = this._settings.get_string(C.Keys.OUTPUT_DEVICE);
        if (device !== '')
            await this._engine.setOutputDevice(device).catch(() => {});

        if (!this._engine || !this._settings)
            return;

        if (this._settings.get_boolean(C.Keys.CLAIM_SINK) &&
            !await this._engine.isDefaultSink())
            await this._engine.claimDefaultSink();
    }

    // GSettings -> filter graph. The gains stored in settings are what the
    // user chose; "off" sends flat instead, leaving the stored curve intact
    // so switching back on restores it.
    _pushToGraph() {
        if (!this._engine || !this._settings)
            return;
        const stored = C.sanitizeGains(
            this._settings.get_value(C.Keys.GAINS).deep_unpack());
        const on = this._settings.get_boolean(C.Keys.ENABLED);
        const gains = on ? stored : C.FLAT;
        const preamp = !on
            ? 0
            : (this._settings.get_boolean(C.Keys.AUTO_PREAMP)
                ? C.autoPreampFor(gains)
                : this._settings.get_double(C.Keys.PREAMP));
        this._engine.apply(gains, preamp);
    }
}
