#!/usr/bin/env python3
"""Generate the GnomeEQ PipeWire filter-chain sink config.

Reproducible: the band table here is the single source of truth for the sink
config; lib/constants.js must agree with it.

Every band is a *peaking* filter, deliberately. A shelf sits at only half its
set gain at its own corner frequency (measured: a lowshelf at 31 Hz with
Gain=+15 gives +7.5 dB at 31 Hz and +14.9 dB at 8 Hz), so shelves at the
extremes would make the 31 Hz and 16 kHz sliders feel dead while wasting
headroom on subsonic/ultrasonic content nobody can hear. Peaking filters put
the gain where the label says it is.
"""
import os
import sys

# (centre frequency Hz, Q).
#
# The ISO 266 one-octave series, phase 0: eleven bands covering the whole
# audible range, 20 Hz to 20 kHz. These are the *nominal* (rounded) preferred
# values that appear on real hardware, which is why 315/630/1250 are not the
# arithmetically exact 320/640/1280 — ISO rounds them. The worst single step is
# 27 cents shy of a true octave, and the geometric mean step is 1.9953
# (0.99658 octaves), so it is an octave grid for every practical purpose.
#
# Q follows from the spacing: Q = sqrt(2**N)/(2**N - 1). At N = 0.99658 that is
# 1.4193, and the classic one-octave 1.4142 is within 0.36% of it — so the
# familiar value is used. (Q must track the spacing: an earlier 1/3-decade grid
# here needed 1.271, and using 1.41 with it would have left gaps between
# neighbours.)
BAND_Q = 1.414
BANDS = [(float(f), BAND_Q) for f in
         (20, 40, 80, 160, 315, 630, 1250, 2500, 5000, 10000, 20000)]

HEADER = """\
# GnomeEQ — 11-band graphic equalizer sink
#
# Generated by tools/gen_sink_conf.py — do not edit by hand.
# Installed to ~/.config/pipewire/filter-chain.conf.d/99-gnomeeq-sink.conf
# and served by the (already enabled) filter-chain.service daemon.
#
# Creates a virtual sink "GnomeEQ". Make it the default output and every app
# is equalized — browser, game, VLC — because apps just follow the default
# sink. Band gains are set LIVE on the node's Props param, so switching a
# preset is instant and never interrupts audio.
context.modules = [
    { name = libpipewire-module-filter-chain
        args = {
            node.description = "GnomeEQ"
            media.name       = "GnomeEQ"
            filter.graph = {
                nodes = [
"""

FOOTER = """\
                ]
            }
            audio.channels = 2
            audio.position = [ FL FR ]
            capture.props = {
                node.name        = "effect_input.gnomeeq"
                node.description = "GnomeEQ"
                node.nick        = "GnomeEQ"
                media.class      = Audio/Sink
                # module-filter-chain leaves its nodes UNregistered by default,
                # which keeps filter internals out of the session manager. For
                # the capture side that is wrong: an unregistered node is never
                # adopted by WirePlumber, so it does not appear in `wpctl
                # status`, GNOME's Sound settings cannot see it, and
                # gsd-media-keys logs "Unable to get default sink" — the volume
                # keys stop working once this sink is the default.
                object.register  = true
                device.icon-name = "audio-card-symbolic"
            }
            playback.props = {
                node.name    = "effect_output.gnomeeq"
                node.passive = true
            }
        }
    }
]
"""


def render():
    out = [HEADER]
    # Preamp: a `linear` builtin whose Mult is a plain linear multiplier
    # (dB -> Mult = 10**(dB/20)). Boosting bands adds headroom pressure, so the
    # preamp exists to pull the whole chain down and avoid clipping. It sits
    # ahead of the bands so the filters never see an already-clipped signal.
    out.append(
        "                    {\n"
        "                        type  = builtin\n"
        "                        name  = preamp\n"
        "                        label = linear\n"
        '                        control = { "Mult" = 1.0 }\n'
        "                    }\n")
    for i, (freq, q) in enumerate(BANDS, start=1):
        out.append(
            f"                    {{\n"
            f"                        type  = builtin\n"
            f"                        name  = eq_band_{i}\n"
            f"                        label = bq_peaking\n"
            f'                        control = {{ "Freq" = {freq} "Q" = {q} "Gain" = 0.0 }}\n'
            f"                    }}\n")
    out.append("                ]\n                links = [\n")
    out.append('                    { output = "preamp:Out" input = "eq_band_1:In" }\n')
    for i in range(1, len(BANDS)):
        out.append(f'                    {{ output = "eq_band_{i}:Out" '
                   f'input = "eq_band_{i + 1}:In" }}\n')
    out.append(FOOTER)
    return "".join(out)


def check_rendered_numbers():
    """Every numeric literal in the rendered config must actually be a number.

    This guards a real bug: the frequency template once appended a literal
    ".0" (correct while the centres were ints), which turned a float centre
    into `"Freq" = 20.0.0`. The daemon still started and the sink still
    appeared, and because graph params cannot be read back there was no way to
    notice from the outside.
    """
    import re
    text = render()
    problems = []
    for name, value in re.findall(r'"(Freq|Q|Gain|Mult)"\s*=\s*(\S+)', text):
        try:
            float(value)
        except ValueError:
            problems.append(f'{name} has a malformed value: {value!r}')
    return problems


def check_constants_js(path):
    """Fail loudly if lib/constants.js has drifted from this band table.

    The frequencies live in two languages: here (to build the filter graph)
    and in constants.js (to label the sliders). If they disagree, a slider
    claims one frequency and adjusts another, which is invisible in testing
    and maddening in use. `make test` runs this.
    """
    import re
    src = open(path).read()
    block = re.search(r"export const BANDS = \[(.*?)\];", src, re.S)
    if not block:
        return ["could not find the BANDS array in constants.js"]
    freqs = [float(m) for m in re.findall(r"freq:\s*([0-9.]+)", block.group(1))]
    problems = []
    if len(freqs) != len(BANDS):
        problems.append(f"band count differs: conf {len(BANDS)}, js {len(freqs)}")
    for i, (js, (conf, _q)) in enumerate(zip(freqs, BANDS), start=1):
        if abs(js - conf) > 0.01:
            problems.append(f"band {i}: conf {conf} Hz vs js {js} Hz")
    return problems


if __name__ == "__main__":
    if "--check" in sys.argv:
        here = os.path.dirname(os.path.abspath(__file__))
        js = os.path.join(os.path.dirname(here),
                          "gnomeeq@vanvonvan.github.io", "lib", "constants.js")
        issues = check_rendered_numbers() + check_constants_js(js)
        for issue in issues:
            print(f"FAIL  {issue}")
        if not issues:
            print(f"ok    rendered config has well-formed numbers")
            print(f"ok    constants.js matches the {len(BANDS)}-band table "
                  f"({BANDS[0][0]} Hz .. {BANDS[-1][0]} Hz, Q={BAND_Q})")
        sys.exit(1 if issues else 0)

    text = render()
    if len(sys.argv) > 1:
        with open(sys.argv[1], "w") as fh:
            fh.write(text)
        print(f"wrote {sys.argv[1]} ({len(text.splitlines())} lines, "
              f"{len(BANDS)} bands)")
    else:
        sys.stdout.write(text)
